# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017
  project: Content Security Policy
  version: 1.0.5
  release: 1.0.5
...
